[files]
"chess_rules.py" = "chess_rules.py"
"ai.py" = "ai.py"

"assets/wking.PNG" = "assets/wking.PNG"
"assets/wqueen.PNG" = "assets/wqueen.PNG"
"assets/wbishop.PNG" = "assets/wbishop.PNG"
"assets/wrook.PNG" = "assets/wrook.PNG"
"assets/wknight.PNG" = "assets/wknight.PNG"
"assets/wpawn.PNG" = "assets/wpawn.PNG"

"assets/bking.PNG" = "assets/bking.PNG"
"assets/bqueen.PNG" = "assets/bqueen.PNG"
"assets/bbishop.PNG" = "assets/bbishop.PNG"
"assets/brook.PNG" = "assets/brook.PNG"
"assets/bknight.PNG" = "assets/bknight.PNG"
"assets/bpawn.PNG" = "assets/bpawn.PNG"
